# Generated by Django 4.2.3 on 2023-12-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childhealthinfo',
            name='otherDisability',
            field=models.CharField(blank=True, default='N/A', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='childhealthinfo',
            name='disability',
            field=models.CharField(choices=[('Cleft Palate', 'Cleft Palate'), ('Cerebral Palsy', 'Cerebral Palsy'), ('Congenital Heart Disease', 'Congenital Heart Disease'), ('Hydrocepalus', 'Hydrocepalus'), ('Down Syndrome', 'Down Syndrome'), ('Global Development Delay', 'Global Development Delay'), ('None', 'None'), ('Others', 'Others')], default='None', max_length=100),
        ),
    ]
