# Generated by Django 4.2.3 on 2023-12-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0002_childhealthinfo_otherdisability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childhealthinfo',
            name='otherDisability',
        ),
    ]
