# Generated by Django 4.2.3 on 2023-12-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0003_remove_childhealthinfo_otherdisability'),
    ]

    operations = [
        migrations.AddField(
            model_name='childhealthinfo',
            name='otherDisability',
            field=models.CharField(blank=True, default='N/A', max_length=255, null=True),
        ),
    ]
