# Generated by Django 4.2.3 on 2023-12-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0005_remove_childhealthinfo_deworming_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childhealthinfo',
            name='otherDisability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='primarychild',
            name='caregiverContact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
