# Generated by Django 4.2.3 on 2023-12-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0011_alter_primarychild_birthorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarychild',
            name='fatherContact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='primarychild',
            name='motherAge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
