# Generated by Django 3.1.12 on 2025-01-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
            ],
        ),
    ]
