# Generated by Django 4.2.6 on 2023-11-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
            ],
        ),
    ]
