# Generated by Django 3.1.12 on 2025-01-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
